import type { ReferenceObject, SchemaObject } from '@nestjs/swagger/dist/interfaces/open-api-spec.interface';

type ContractSchema = SchemaObject | ReferenceObject;

const string = (options: SchemaObject = {}): SchemaObject => ({ type: 'string', ...options });
const number = (options: SchemaObject = {}): SchemaObject => ({ type: 'number', ...options });
const integer = (options: SchemaObject = {}): SchemaObject => ({ type: 'integer', ...options });
const boolean = (options: SchemaObject = {}): SchemaObject => ({ type: 'boolean', ...options });
const ref = (name: string): ReferenceObject => ({ $ref: `#/components/schemas/${name}` });
const nullableRef = (name: string): SchemaObject => ({ allOf: [ref(name)], nullable: true });
const array = (items: ContractSchema, options: SchemaObject = {}): SchemaObject => ({ type: 'array', items, ...options });
const object = (
  properties: Record<string, ContractSchema>,
  required: string[] = [],
  options: SchemaObject = {},
): SchemaObject => {
  const unknownRequired = required.filter((name) => !(name in properties));
  if (unknownRequired.length) {
    throw new Error(`Object schema requires undefined properties: ${unknownRequired.join(', ')}`);
  }
  return {
    type: 'object',
    ...(required.length ? { required } : {}),
    properties,
    ...options,
  };
};
const request = (properties: Record<string, ContractSchema>, required: string[] = []): SchemaObject =>
  object(properties, required, { additionalProperties: false });

const uuid = () => string({ format: 'uuid' });
const dateTime = () => string({ format: 'date-time' });
const nullableString = () => string({ nullable: true });
const nullableDateTime = () => dateTimeWith({ nullable: true });
const dateTimeWith = (options: SchemaObject): SchemaObject => string({ format: 'date-time', ...options });
const enumString = (values: string[], options: SchemaObject = {}): SchemaObject => string({ enum: values, ...options });

const discoveryAudience = ['public', 'mutuals', 'close_buddies'];
const postVisibility = ['public', 'followers', 'mutuals', 'close_buddies', 'only_me'];
const reportCategories = ['spam', 'harassment', 'hate', 'sexual_content', 'violence', 'self_harm', 'scam', 'privacy', 'impersonation', 'illegal_activity', 'other'];
const activityPersonas = ['runner', 'bodybuilder', 'cyclist', 'yogi', 'swimmer', 'powerlifter', 'crossfitter', 'walker', 'hiker', 'climber', 'martial_artist', 'dancer', 'pilates', 'calisthenics', 'rower', 'triathlete', 'soccer_player', 'basketball_player', 'other'];

const messageReferenceProperties: Record<string, ContractSchema> = {
  referenceType: enumString(['actsnap', 'message'], { nullable: true }),
  referenceId: nullableString(),
  referenceMediaUrl: nullableString(),
  referenceText: nullableString(),
  referenceAuthorName: nullableString(),
};

const reportRequestProperties: Record<string, ContractSchema> = {
  reason: enumString(['spam', 'harassment', 'nudity', 'violence', 'other']),
  category: enumString(reportCategories),
  note: string({ maxLength: 1000 }),
  details: string({ maxLength: 1000 }),
};

/**
 * Schemas that Nest cannot infer from erased TypeScript return types.  They are
 * intentionally shared by operations instead of being duplicated as hundreds
 * of controller decorators.
 */
export const AUTHORITATIVE_CONTRACT_SCHEMAS: Record<string, SchemaObject> = {
  JsonObject: {
    type: 'object',
    additionalProperties: true,
    'x-swebudd-arbitrary-json': true,
  } as SchemaObject,
  ApiErrorResponse: object({
    statusCode: integer(),
    message: {
      oneOf: [string(), array(string())],
    },
    error: string(),
    timestamp: dateTime(),
    path: string(),
  }, ['statusCode', 'message']),

  CountResponse: object({ count: integer({ minimum: 0 }) }, ['count']),
  OkResponse: object({ ok: boolean() }, ['ok']),
  LikeStateResponse: object({ liked: boolean() }, ['liked']),
  SaveStateResponse: object({ saved: boolean() }, ['saved']),
  HiddenStateResponse: object({ hidden: boolean() }, ['hidden']),
  BlockStateResponse: object({ blocked: boolean() }, ['blocked']),
  CloseBuddyStateResponse: object({ closeBuddy: boolean() }, ['closeBuddy']),
  ViewedStateResponse: object({ viewed: boolean() }, ['viewed']),
  HealthLiveResponse: object({
    ok: boolean(),
    version: string(),
    uptime: integer({ minimum: 0 }),
    timestamp: dateTime(),
  }, ['ok', 'version', 'uptime', 'timestamp']),
  HealthReadyResponse: object({
    ok: boolean(),
    database: enumString(['ok']),
    version: string(),
    timestamp: dateTime(),
  }, ['ok', 'database', 'version', 'timestamp']),

  FeedViewedDto: request({ postIds: array(uuid(), { maxItems: 100 }) }, ['postIds']),
  MultipartFileDto: object({ file: string({ format: 'binary' }) }, ['file'], { additionalProperties: false }),
  MultipartFilesDto: object({ files: array(string({ format: 'binary' }), { minItems: 1, maxItems: 6 }) }, ['files'], { additionalProperties: false }),
  RegisterChatKeyDto: request({ publicKey: string({ maxLength: 4096 }) }, ['publicKey']),
  ConnectIntegrationDto: request({
    provider: enumString(['strava', 'garmin']),
    providerUserId: string(),
    scopes: array(string()),
    tokenExpiresAt: dateTime(),
  }, ['provider']),
  UpdateIntegrationDto: request({
    status: enumString(['connected', 'disconnected', 'revoked', 'error']),
    lastSyncError: string(),
    lastSyncAt: dateTime(),
  }),
  CreateActivityDto: request({
    integrationId: uuid(),
    source: enumString(['manual', 'strava', 'garmin']),
    externalId: string(),
    type: string(),
    title: string(),
    startedAt: dateTime(),
    durationSeconds: integer({ minimum: 0 }),
    distanceMeters: number({ minimum: 0 }),
    elevationGainMeters: number({ minimum: 0 }),
    calories: integer({ minimum: 0 }),
    averageHeartRate: integer({ minimum: 0 }),
    maxHeartRate: integer({ minimum: 0 }),
    averagePaceSecondsKm: integer({ minimum: 0 }),
    averageSpeedMetersSec: number({ minimum: 0 }),
    raw: ref('JsonObject'),
  }, ['type', 'startedAt']),
  UpdateActivityDto: request({
    integrationId: uuid(),
    source: enumString(['manual', 'strava', 'garmin']),
    externalId: string(),
    type: string(),
    title: string(),
    startedAt: dateTime(),
    durationSeconds: integer({ minimum: 0 }),
    distanceMeters: number({ minimum: 0 }),
    elevationGainMeters: number({ minimum: 0 }),
    calories: integer({ minimum: 0 }),
    averageHeartRate: integer({ minimum: 0 }),
    maxHeartRate: integer({ minimum: 0 }),
    averagePaceSecondsKm: integer({ minimum: 0 }),
    averageSpeedMetersSec: number({ minimum: 0 }),
    raw: ref('JsonObject'),
  }, ['type', 'startedAt']),

  UpdateMeDto: request({
    displayName: string(),
    username: string({ minLength: 3, maxLength: 32 }),
    bio: nullableString(),
    profileImageUrl: nullableString(),
    coverImageUrl: nullableString(),
    gender: enumString(['female', 'male', 'non_binary', 'prefer_not_to_say', 'other'], { nullable: true }),
    dateOfBirth: dateTimeWith({ nullable: true }),
    activityPersona: enumString(activityPersonas, { nullable: true }),
    activityPersonas: array(enumString(activityPersonas)),
    profileVisibility: enumString(['public', 'followers', 'mutuals', 'close_buddies', 'private']),
    defaultPostVisibility: enumString(postVisibility),
    hideProfileBadges: boolean(),
    hiddenProfileBadgeCodes: array(string()),
    latitude: number({ nullable: true, minimum: -90, maximum: 90, writeOnly: true }),
    longitude: number({ nullable: true, minimum: -180, maximum: 180, writeOnly: true }),
  }),
  CompleteUserOnboardingDto: request({
    username: string({ minLength: 3 }),
    dateOfBirth: dateTime(),
    legalConsent: boolean(),
    dataConsent: boolean(),
    activityPersonas: array(enumString(activityPersonas)),
  }, ['username', 'dateOfBirth', 'legalConsent', 'dataConsent']),
  UpdateAccountDto: request({
    email: string({ format: 'email', maxLength: 254 }),
    currentPassword: string({ format: 'password', writeOnly: true }),
  }, ['email', 'currentPassword']),
  UpdatePasswordDto: request({
    currentPassword: string({ format: 'password', writeOnly: true }),
    newPassword: string({ format: 'password', minLength: 8, writeOnly: true }),
  }, ['currentPassword', 'newPassword']),
  DeleteMeDto: request({ confirmation: string({ minLength: 1, maxLength: 80 }) }, ['confirmation']),
  ReportUserDto: request(reportRequestProperties),
  SaveSearchHistoryDto: request({
    type: enumString(['term', 'user']),
    term: string({ maxLength: 120 }),
    targetUserId: uuid(),
    displayName: string({ nullable: true, maxLength: 120 }),
    username: string({ nullable: true, maxLength: 64 }),
    profileImageUrl: string({ nullable: true, maxLength: 1000 }),
  }, ['type']),

  UpdatePostDto: request({
    text: string({ maxLength: 1000 }),
    visibility: enumString(postVisibility),
    privacy: enumString(postVisibility),
    activityId: uuid(),
    images: array(ref('PostImageDto'), { maxItems: 10 }),
    taggedUserIds: array(uuid(), { maxItems: 50 }),
    taggedUsers: array(uuid(), { maxItems: 50 }),
  }),
  RepostDto: request({ text: string({ maxLength: 500 }) }),
  ReportPostDto: request(reportRequestProperties),
  CommentDto: request({
    body: string({ maxLength: 500 }),
    parentId: uuid(),
    images: array(ref('PostImageDto'), { maxItems: 1 }),
  }),
  UpdateCommentDto: request({ body: string({ maxLength: 500 }) }, ['body']),

  CreateGroupDto: request({
    name: string({ maxLength: 120 }),
    slug: string({ pattern: '^[a-z0-9-]{3,60}$' }),
    description: string({ maxLength: 500 }),
    visibility: enumString(['public', 'private']),
    inviteUserIds: array(uuid(), { maxItems: 50 }),
  }, ['name', 'slug']),
  InviteGroupUsersDto: request({ userIds: array(uuid(), { maxItems: 50 }) }, ['userIds']),
  UpdateGroupSettingsDto: request({
    name: string({ maxLength: 120 }),
    description: string({ maxLength: 500 }),
    profileImageUrl: string(),
    coverImageUrl: string(),
    visibility: enumString(['public', 'private']),
    allowAnonymousPosts: boolean(),
  }),
  ReportGroupDto: request(reportRequestProperties),
  UpdateGroupRoleDto: request({ role: enumString(['owner', 'admin', 'moderator', 'member']) }, ['role']),
  GroupPostDto: request({
    text: string({ maxLength: 1000 }),
    anonymous: boolean(),
    images: array(ref('PostImageDto'), { maxItems: 10 }),
  }),
  GroupChatMuteDto: request({ muted: boolean(), mutedUntil: dateTimeWith({ nullable: true }) }, ['muted']),
  GroupChatPinDto: request({ pinned: boolean() }, ['pinned']),
  CreateGroupChannelDto: request({
    name: string({ pattern: '^[A-Za-z0-9][A-Za-z0-9 -]{1,38}[A-Za-z0-9]$' }),
    description: string({ maxLength: 160 }),
    visibility: enumString(['public', 'private']),
    messagePolicy: enumString(['everyone', 'moderators', 'admins']),
    memberIds: array(uuid(), { maxItems: 50 }),
  }, ['name']),
  GroupMessageDto: request({
    body: string({ maxLength: 1000 }),
    referenceType: enumString(['message']),
    referenceId: string({ maxLength: 120 }),
    referenceText: string({ maxLength: 500 }),
    referenceAuthorName: string({ maxLength: 120 }),
  }, ['body']),

  SendDirectMessageDto: request({
    recipientId: uuid(),
    body: string({ maxLength: 4000 }),
    encrypted: boolean({ enum: [false] }),
    referenceType: enumString(['actsnap', 'message']),
    referenceId: string({ maxLength: 120 }),
    referenceMediaUrl: string({ maxLength: 12000 }),
    referenceText: string({ maxLength: 500 }),
    referenceAuthorName: string({ maxLength: 120 }),
  }, ['recipientId', 'body']),
  UpdateChatProfileDto: request({
    displayName: string({ maxLength: 120 }),
    profileImageUrl: string({ maxLength: 12000 }),
  }),
  ChatMuteDto: request({ muted: boolean(), mutedUntil: dateTimeWith({ nullable: true }) }, ['muted']),
  ChatPinDto: request({ pinned: boolean() }, ['pinned']),
  MessageReactionDto: request({ emoji: string({ maxLength: 32 }) }, ['emoji']),
  ReportMessageDto: request({
    category: enumString(reportCategories),
    note: string({ maxLength: 1000 }),
    details: string({ maxLength: 1000 }),
  }),
  CreateBuddyGroupChatDto: request({
    name: string({ maxLength: 80 }),
    description: string({ maxLength: 240 }),
    participantIds: array(uuid(), { minItems: 1, maxItems: 50 }),
  }, ['name', 'participantIds']),
  AddBuddyGroupParticipantsDto: request({ participantIds: array(uuid(), { minItems: 1, maxItems: 50 }) }, ['participantIds']),
  SendBuddyGroupMessageDto: request({
    body: string({ maxLength: 4000 }),
    referenceType: enumString(['message']),
    referenceId: string({ maxLength: 120 }),
    referenceText: string({ maxLength: 500 }),
    referenceAuthorName: string({ maxLength: 120 }),
  }, ['body']),

  UpsertBuddySessionDto: request({
    activity: string({ maxLength: 60, nullable: true }),
    subActivity: string({ maxLength: 60 }),
    note: string({ maxLength: 120 }),
    visibleTo: enumString(discoveryAudience),
    canSee: enumString(discoveryAudience),
    roomId: string({ format: 'uuid', nullable: true }),
    latitude: number({ minimum: -90, maximum: 90, writeOnly: true }),
    longitude: number({ minimum: -180, maximum: 180, writeOnly: true }),
    ttlMinutes: number({ minimum: 5, maximum: 120 }),
  }, ['latitude', 'longitude']),
  UpdateBuddySessionRecapDto: request({
    title: string({ maxLength: 100 }),
    caption: string({ nullable: true, maxLength: 1000 }),
    areaLabel: string({ nullable: true, maxLength: 120 }),
    includeParticipants: boolean(),
    includeBroadArea: boolean(),
    visibility: enumString(postVisibility),
  }),
  ShareBuddySessionRecapDto: request({
    title: string({ maxLength: 100 }),
    caption: string({ nullable: true, maxLength: 1000 }),
    areaLabel: string({ nullable: true, maxLength: 120 }),
    includeParticipants: boolean(),
    includeBroadArea: boolean(),
    visibility: enumString(postVisibility),
    target: enumString(['feed', 'group']),
  }),
  CreateBuddyRoomDto: request({
    name: string({ maxLength: 80 }),
    scope: enumString(['public', 'group']),
    visibility: enumString(['public', 'private']),
    groupId: uuid(),
    activity: string({ nullable: true, maxLength: 60 }),
    subActivity: string({ maxLength: 60 }),
    ttlMinutes: number({ minimum: 15, maximum: 360 }),
  }),
  UpdateBuddyRoomDto: request({
    activity: string({ nullable: true, maxLength: 60 }),
    subActivity: string({ nullable: true, maxLength: 60 }),
  }),
  JoinBuddyRoomDto: request({
    roomId: uuid(),
    code: string({ maxLength: 24 }),
    latitude: number({ minimum: -90, maximum: 90, writeOnly: true }),
    longitude: number({ minimum: -180, maximum: 180, writeOnly: true }),
  }, ['latitude', 'longitude']),
  InviteBuddyRoomDto: request({
    recipientIds: array(uuid(), { minItems: 1, maxItems: 50 }),
    inviteUrl: string({ maxLength: 1000 }),
    message: string({ maxLength: 500 }),
  }, ['recipientIds']),
  PinBuddyRoomLocationDto: request({
    latitude: number({ minimum: -90, maximum: 90, writeOnly: true }),
    longitude: number({ minimum: -180, maximum: 180, writeOnly: true }),
    label: string({ maxLength: 80 }),
  }, ['latitude', 'longitude']),
  PinBuddyRoomPersonalLocationDto: request({
    latitude: number({ minimum: -90, maximum: 90, writeOnly: true }),
    longitude: number({ minimum: -180, maximum: 180, writeOnly: true }),
    label: string({ maxLength: 80 }),
  }, ['latitude', 'longitude']),
  SendBuddySessionMessageDto: request({
    kind: enumString(['text', 'gif']),
    body: string({ maxLength: 1000 }),
    referenceType: enumString(['message']),
    referenceId: string({ maxLength: 120 }),
    referenceText: string({ maxLength: 500 }),
    referenceAuthorName: string({ maxLength: 120 }),
  }, ['body']),
  BuddySessionMessageReactionDto: request({ emoji: string({ maxLength: 32 }) }, ['emoji']),
  KickBuddyRoomParticipantDto: request({ reason: string({ maxLength: 240 }) }),
  UpdateBuddyRoomParticipantRoleDto: request({ role: enumString(['admin', 'member']) }, ['role']),

  CreateStoryDto: request({
    text: string({ maxLength: 500 }),
    textPlacement: enumString(['caption', 'overlay']),
    mediaUrl: string(),
    mediaType: enumString(['image', 'video']),
    mimeType: string(),
    filename: string(),
    visibility: enumString(postVisibility),
  }),
  ReactStoryDto: request({ emoji: enumString(['🔥', '💪', '👏', '😍', '😂', '😮']) }, ['emoji']),
  ReplyStoryDto: request({ body: string({ maxLength: 1000 }) }, ['body']),

  AccountSessionResponse: object({
    id: uuid(),
    createdAt: dateTime(),
    expiresAt: dateTime(),
    revokedAt: nullableDateTime(),
    current: boolean(),
    active: boolean(),
    deviceLabel: nullableString(),
    locationLabel: nullableString(),
    ipAddress: nullableString(),
    userAgent: nullableString(),
  }, ['id', 'createdAt', 'expiresAt', 'revokedAt', 'current', 'active', 'deviceLabel', 'locationLabel', 'ipAddress', 'userAgent']),
  AccountSessionListResponse: array(ref('AccountSessionResponse')),
  SearchHistoryResponse: object({
    id: uuid(),
    type: enumString(['term', 'user']),
    term: nullableString(),
    targetUserId: nullableString(),
    displayName: nullableString(),
    username: nullableString(),
    profileImageUrl: nullableString(),
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }, ['id', 'type', 'term', 'targetUserId', 'displayName', 'username', 'profileImageUrl', 'createdAt', 'updatedAt']),
  SearchHistoryListResponse: array(ref('SearchHistoryResponse')),
  FollowRequestResponse: object({
    id: uuid(),
    requesterId: uuid(),
    recipientId: uuid(),
    status: enumString(['pending', 'accepted', 'declined']),
    createdAt: dateTime(),
    updatedAt: dateTime(),
    requester: ref('PublicUserResponse'),
    recipient: ref('PublicUserResponse'),
  }, ['id', 'requesterId', 'recipientId', 'status', 'createdAt', 'updatedAt']),
  FollowRequestListResponse: array(ref('FollowRequestResponse')),
  FollowActionResponse: {
    oneOf: [
      object({
        status: enumString(['following']),
        follow: object({ followerId: uuid(), followingId: uuid(), createdAt: dateTime() }, ['followerId', 'followingId', 'createdAt']),
      }, ['status', 'follow']),
      object({
        status: enumString(['requested']),
        request: object({
          id: uuid(),
          requesterId: uuid(),
          recipientId: uuid(),
          status: enumString(['pending']),
          createdAt: dateTime(),
          updatedAt: dateTime(),
        }, ['id', 'requesterId', 'recipientId', 'status', 'createdAt', 'updatedAt']),
      }, ['status', 'request']),
    ],
  },
  FollowRequestStatusResponse: object({
    status: enumString(['following', 'declined']),
    follow: object({ followerId: uuid(), followingId: uuid(), createdAt: dateTime() }, ['followerId', 'followingId', 'createdAt']),
  }, ['status']),
  PublicUserListResponse: array(ref('PublicUserResponse')),

  PostHistoryResponse: object({
    id: uuid(),
    oldText: nullableString(),
    newText: nullableString(),
    createdAt: dateTime(),
  }, ['id', 'oldText', 'newText', 'createdAt']),
  PostHistoryListResponse: array(ref('PostHistoryResponse')),
  CommentHistoryResponse: object({
    id: uuid(),
    commentId: uuid(),
    editorId: uuid(),
    oldBody: string(),
    newBody: string(),
    createdAt: dateTime(),
  }, ['id', 'commentId', 'editorId', 'oldBody', 'newBody', 'createdAt']),
  CommentHistoryListResponse: array(ref('CommentHistoryResponse')),
  CommentPageResponse: object({
    items: array(ref('CommentResponse')),
    nextCursor: integer({ nullable: true, minimum: 0 }),
  }, ['items', 'nextCursor']),
  RepostResponse: object({
    id: uuid(),
    userId: uuid(),
    postId: uuid(),
    text: nullableString(),
    likeCount: integer({ minimum: 0 }),
    createdAt: dateTime(),
    post: ref('FeedPostResponse'),
    user: ref('PublicUserResponse'),
  }, ['id', 'userId', 'postId', 'text', 'likeCount', 'createdAt', 'post']),

  GroupMemberResponse: object({
    userId: uuid(),
    role: enumString(['owner', 'admin', 'moderator', 'member']),
    joinedAt: dateTime(),
    user: ref('PublicUserResponse'),
  }, ['userId', 'role', 'joinedAt', 'user']),
  GroupCapabilitiesResponse: object({
    manageSettings: boolean(),
    manageRoles: boolean(),
    moderatePosts: boolean(),
    createChannels: boolean(),
    createPosts: boolean(),
  }, ['manageSettings', 'manageRoles', 'moderatePosts', 'createChannels', 'createPosts']),
  GroupResponse: object({
    id: uuid(),
    name: string(),
    slug: string(),
    description: nullableString(),
    profileImageUrl: nullableString(),
    coverImageUrl: nullableString(),
    visibility: enumString(['public', 'private']),
    inviteCode: nullableString(),
    allowAnonymousPosts: boolean(),
    createdAt: dateTime(),
    isMember: boolean(),
    muted: boolean(),
    pinned: boolean(),
    unreadCount: integer({ minimum: 0 }),
    lastMessage: nullableRef('GroupMessageResponse'),
    chatChannels: array(ref('GroupChannelResponse')),
    messages: array(ref('GroupMessageResponse')),
    posts: array(ref('FeedPostResponse')),
    members: array(ref('GroupMemberResponse')),
    capabilities: ref('GroupCapabilitiesResponse'),
    _count: object({
      members: integer({ minimum: 0 }),
      posts: integer({ minimum: 0 }),
      messages: integer({ minimum: 0 }),
      chatChannels: integer({ minimum: 0 }),
    }, ['members', 'posts', 'messages']),
  }, ['id', 'name', 'slug', 'visibility']),
  GroupListResponse: array(ref('GroupResponse')),
  GroupInviteResponse: object({
    id: uuid(),
    groupId: uuid(),
    inviterId: uuid(),
    inviteeId: uuid(),
    status: enumString(['pending', 'accepted', 'declined', 'cancelled']),
    createdAt: dateTime(),
    respondedAt: nullableDateTime(),
    inviter: nullableRef('PublicUserResponse'),
    group: ref('GroupResponse'),
  }, ['id', 'groupId', 'inviterId', 'inviteeId', 'status', 'createdAt', 'respondedAt', 'inviter', 'group']),
  GroupInviteListResponse: array(ref('GroupInviteResponse')),
  InviteUsersResponse: object({
    sent: integer({ minimum: 0 }),
    recipients: array(ref('PublicUserResponse')),
  }, ['sent', 'recipients']),
  GroupChannelResponse: object({
    id: uuid(),
    groupId: uuid(),
    creatorId: uuid(),
    name: string(),
    description: nullableString(),
    visibility: enumString(['public', 'private']),
    messagePolicy: enumString(['everyone', 'moderators', 'admins']),
    createdAt: dateTime(),
    creator: ref('PublicUserResponse'),
    allowedUsers: array(object({ userId: uuid() }, ['userId'])),
    unreadCount: integer({ minimum: 0 }),
    muted: boolean(),
    pinned: boolean(),
    _count: object({ messages: integer({ minimum: 0 }) }, ['messages']),
  }, ['id', 'groupId', 'creatorId', 'name', 'description', 'visibility', 'messagePolicy', 'createdAt', 'creator', 'allowedUsers', '_count']),
  GroupChannelListResponse: array(ref('GroupChannelResponse')),
  MessageChannelSummaryResponse: object({ id: uuid(), name: string() }, ['id', 'name']),
  GroupMessageResponse: object({
    id: uuid(),
    groupId: nullableString(),
    channelId: nullableString(),
    senderId: uuid(),
    recipientId: nullableString(),
    buddyGroupChatId: nullableString(),
    body: string(),
    ciphertext: nullableString(),
    nonce: nullableString(),
    encrypted: boolean(),
    readAt: nullableDateTime(),
    ...messageReferenceProperties,
    deletedAt: nullableDateTime(),
    deletedById: nullableString(),
    createdAt: dateTime(),
    sender: ref('PublicUserResponse'),
    channel: nullableRef('MessageChannelSummaryResponse'),
    reactions: array(object({ emoji: string(), userId: uuid() }, ['emoji', 'userId'])),
    pinned: boolean(),
    readBy: array(object({
      userId: uuid(),
      readAt: dateTime(),
      user: nullableRef('PublicUserResponse'),
    }, ['userId', 'readAt', 'user'])),
  }, ['id', 'groupId', 'channelId', 'senderId', 'recipientId', 'buddyGroupChatId', 'body', 'ciphertext', 'nonce', 'encrypted', 'readAt', 'referenceType', 'referenceId', 'referenceMediaUrl', 'referenceText', 'referenceAuthorName', 'deletedAt', 'deletedById', 'createdAt', 'sender', 'channel', 'reactions']),
  GroupMessageListResponse: array(ref('GroupMessageResponse')),
  GroupMuteResponse: object({ groupId: uuid(), muted: boolean(), mutedUntil: nullableDateTime() }, ['groupId', 'muted', 'mutedUntil']),
  GroupPinResponse: object({ groupId: uuid(), pinned: boolean() }, ['groupId', 'pinned']),
  GroupChannelMuteResponse: object({ groupId: uuid(), channelId: uuid(), muted: boolean(), mutedUntil: nullableDateTime() }, ['groupId', 'channelId', 'muted', 'mutedUntil']),
  GroupChannelPinResponse: object({ groupId: uuid(), channelId: uuid(), pinned: boolean() }, ['groupId', 'channelId', 'pinned']),
  GroupChannelReadResponse: object({
    groupId: uuid(), channelId: uuid(), userId: uuid(), readAt: dateTime(), user: nullableRef('PublicUserResponse'),
  }, ['groupId', 'channelId', 'userId', 'readAt', 'user']),

  ChatProfileOverrideResponse: object({
    id: uuid(), ownerId: uuid(), peerId: uuid(), displayName: nullableString(), profileImageUrl: nullableString(), createdAt: dateTime(), updatedAt: dateTime(),
  }, ['id', 'ownerId', 'peerId', 'displayName', 'profileImageUrl', 'createdAt', 'updatedAt']),
  ChatKeyResponse: object({ id: uuid(), chatPublicKey: nullableString() }, ['id', 'chatPublicKey']),
  BuddyProfileResponse: object({
    peer: ref('PublicUserResponse'),
    override: nullableRef('ChatProfileOverrideResponse'),
  }, ['peer']),
  ChatMessageResponse: object({
    id: uuid(),
    senderId: uuid(),
    recipientId: nullableString(),
    groupId: nullableString(),
    channelId: nullableString(),
    buddyGroupChatId: nullableString(),
    body: string(),
    ciphertext: nullableString(),
    nonce: nullableString(),
    encrypted: boolean(),
    readAt: nullableDateTime(),
    deletedAt: nullableDateTime(),
    deletedById: nullableString(),
    createdAt: dateTime(),
    sender: ref('PublicUserResponse'),
    recipient: nullableRef('PublicUserResponse'),
    group: object({ id: uuid(), name: string(), slug: string() }, ['id', 'name'], { nullable: true }),
    channel: nullableRef('MessageChannelSummaryResponse'),
    buddyGroupChat: object({ id: uuid(), name: string() }, ['id', 'name'], { nullable: true }),
    reactions: array(object({ emoji: string(), userId: uuid() }, ['emoji', 'userId'])),
    pinned: boolean(),
    ...messageReferenceProperties,
  }, ['id', 'senderId', 'recipientId', 'groupId', 'channelId', 'buddyGroupChatId', 'body', 'ciphertext', 'nonce', 'encrypted', 'readAt', 'deletedAt', 'deletedById', 'createdAt', 'sender', 'recipient', 'reactions', 'referenceType', 'referenceId', 'referenceMediaUrl', 'referenceText', 'referenceAuthorName']),
  ChatMessageListResponse: array(ref('ChatMessageResponse')),
  MessageRequestResponse: object({
    id: uuid(), senderId: uuid(), recipientId: uuid(), body: string(), status: enumString(['pending', 'accepted', 'declined']), sender: ref('PublicUserResponse'), recipient: ref('PublicUserResponse'), createdAt: dateTime(), updatedAt: dateTime(), ...messageReferenceProperties,
  }, ['id', 'senderId', 'recipientId', 'body', 'status', 'sender', 'recipient', 'createdAt', 'updatedAt', 'referenceType', 'referenceId', 'referenceMediaUrl', 'referenceText', 'referenceAuthorName']),
  ChatRequestResultResponse: { oneOf: [ref('MessageRequestResponse'), ref('ChatMessageResponse')] },
  MessageRequestListResponse: array(ref('MessageRequestResponse')),
  ChatConversationResponse: object({
    peer: ref('PublicUserResponse'),
    lastMessage: nullableRef('ChatMessageResponse'),
    unreadCount: integer({ minimum: 0 }),
    muted: boolean(),
    pinned: boolean(),
  }, ['peer', 'lastMessage', 'unreadCount', 'muted', 'pinned']),
  ChatConversationListResponse: array(ref('ChatConversationResponse')),
  BuddyGroupMemberResponse: object({
    userId: uuid(), joinedAt: dateTime(), user: ref('PublicUserResponse'),
  }, ['userId', 'joinedAt', 'user']),
  BuddyGroupChatResponse: object({
    id: uuid(), creatorId: uuid(), name: string(), description: nullableString(), createdAt: dateTime(), updatedAt: dateTime(),
    members: array(ref('BuddyGroupMemberResponse')),
    lastMessage: nullableRef('ChatMessageResponse'),
    unreadCount: integer({ minimum: 0 }),
    muted: boolean(),
    pinned: boolean(),
    _count: object({ members: integer({ minimum: 0 }), messages: integer({ minimum: 0 }) }, ['members', 'messages']),
  }, ['id', 'creatorId', 'name', 'description', 'createdAt', 'updatedAt', 'members', 'lastMessage', '_count']),
  BuddyGroupChatListResponse: array(ref('BuddyGroupChatResponse')),
  DirectMuteResponse: object({ peerId: uuid(), muted: boolean(), mutedUntil: nullableDateTime() }, ['peerId', 'muted']),
  DirectPinResponse: object({ peerId: uuid(), pinned: boolean() }, ['peerId', 'pinned']),
  BuddyGroupMuteResponse: object({ buddyGroupChatId: uuid(), muted: boolean(), mutedUntil: nullableDateTime() }, ['buddyGroupChatId', 'muted']),
  BuddyGroupPinResponse: object({ buddyGroupChatId: uuid(), pinned: boolean() }, ['buddyGroupChatId', 'pinned']),
  BuddyGroupReadResponse: object({ ok: boolean(), buddyGroupChatId: uuid(), userId: uuid(), readAt: dateTime() }, ['ok', 'buddyGroupChatId', 'userId', 'readAt']),
  DirectReadResponse: object({ count: integer({ minimum: 0 }), readCount: integer({ minimum: 0 }), readAt: dateTime() }, ['count', 'readCount', 'readAt']),
  MessagePinResponse: object({ messageId: uuid(), pinned: boolean() }, ['messageId', 'pinned']),
  MessageReadByResponse: object({ userId: uuid(), lastReadAt: dateTime(), user: nullableRef('PublicUserResponse') }, ['userId', 'lastReadAt', 'user']),
  MessageInfoResponse: object({
    message: ref('ChatMessageResponse'), readBy: array(ref('MessageReadByResponse')), directReadAt: nullableDateTime(),
  }, ['message', 'readBy', 'directReadAt']),
  ChatSearchResultResponse: object({
    kind: enumString(['direct', 'group', 'buddyGroup']), message: ref('ChatMessageResponse'),
  }, ['kind', 'message']),
  ChatSearchResultListResponse: array(ref('ChatSearchResultResponse')),

  BuddyActivityOptionResponse: object({ value: string(), label: string(), subActivities: array(string()) }, ['value', 'label', 'subActivities']),
  BuddyActivityOptionListResponse: array(ref('BuddyActivityOptionResponse')),
  BuddyRoomPinResponse: object({ latitude: number(), longitude: number(), label: nullableString(), pinnedById: nullableString(), pinnedAt: nullableDateTime() }, ['latitude', 'longitude', 'label', 'pinnedById', 'pinnedAt']),
  BuddyRoomPersonalPinResponse: object({ latitude: number(), longitude: number(), label: nullableString(), pinnedAt: nullableDateTime() }, ['latitude', 'longitude', 'label', 'pinnedAt']),
  BuddyRoomParticipantResponse: object({
    userId: uuid(), role: enumString(['owner', 'admin', 'member']), joinedAt: dateTime(), lastActivityAt: nullableDateTime(), leftAt: nullableDateTime(), kickedAt: nullableDateTime(), personalPin: nullableRef('BuddyRoomPersonalPinResponse'), user: nullableRef('BuddyUserResponse'),
  }, ['userId', 'role', 'joinedAt', 'lastActivityAt', 'leftAt', 'kickedAt', 'personalPin', 'user']),
  BuddyRoomResponse: object({
    id: uuid(), name: string(), scope: enumString(['public', 'group']), visibility: enumString(['public', 'private']), code: string(), groupId: nullableString(),
    group: object({ id: uuid(), name: string(), slug: string() }, ['id', 'name', 'slug'], { nullable: true }),
    creatorId: uuid(), creator: ref('PublicUserResponse'), activity: nullableString(), subActivity: nullableString(), pinnedLocation: nullableRef('BuddyRoomPinResponse'), expiresAt: dateTime(), createdAt: dateTime(), participantCount: integer({ minimum: 0 }), participants: array(ref('BuddyRoomParticipantResponse')), activeSessions: array(ref('BuddySessionResponse')),
  }, ['id', 'name', 'scope', 'visibility', 'groupId', 'group', 'creatorId', 'activity', 'subActivity', 'pinnedLocation', 'expiresAt', 'createdAt', 'participantCount']),
  BuddyRoomListResponse: array(ref('BuddyRoomResponse')),
  BuddyUserResponse: object({
    id: uuid(),
    displayName: nullableString(),
    username: nullableString(),
    profileImageUrl: nullableString(),
    age: integer({ nullable: true, minimum: 0 }),
  }, ['id', 'displayName', 'username', 'profileImageUrl', 'age']),
  BuddySessionResponse: object({
    id: uuid(), userId: uuid(), roomId: nullableString(), room: nullableRef('BuddyRoomResponse'), activity: nullableString(), subActivity: nullableString(), note: nullableString(), visibleTo: enumString(discoveryAudience), canSee: enumString(discoveryAudience), latitude: number(), longitude: number(), expiresAt: dateTime(), updatedAt: dateTime(), distanceKm: number({ minimum: 0 }), user: ref('BuddyUserResponse'),
  }, ['id', 'userId', 'roomId', 'room', 'activity', 'subActivity', 'note', 'visibleTo', 'canSee', 'latitude', 'longitude', 'expiresAt', 'updatedAt', 'distanceKm', 'user']),
  NullableBuddySessionResponse: { oneOf: [ref('BuddySessionResponse')], nullable: true },
  BuddySessionListResponse: array(ref('BuddySessionResponse')),
  BuddySessionMessageResponse: object({
    id: string(), roomId: uuid(), senderId: uuid(), kind: enumString(['text', 'gif', 'sticker', 'joined', 'left', 'kicked']), body: string(), referenceType: enumString(['message'], { nullable: true }), referenceId: nullableString(), referenceText: nullableString(), referenceAuthorName: nullableString(), deletedAt: nullableDateTime(), deletedById: nullableString(), createdAt: dateTime(), sender: ref('PublicUserResponse'), readBy: array(object({ userId: uuid(), readAt: dateTime(), user: nullableRef('PublicUserResponse') }, ['userId', 'readAt', 'user'])), reactions: array(object({ emoji: string(), userId: uuid() }, ['emoji', 'userId'])),
  }, ['id', 'roomId', 'senderId', 'kind', 'body', 'referenceType', 'referenceId', 'referenceText', 'referenceAuthorName', 'deletedAt', 'deletedById', 'createdAt', 'sender', 'readBy', 'reactions']),
  BuddySessionMessageListResponse: array(ref('BuddySessionMessageResponse')),
  BuddyStopResponse: object({ ok: boolean(), recap: nullableRef('BuddySessionRecapResponse') }, ['ok', 'recap']),
  BuddySessionRecapResponse: {
    allOf: [
      ref('PublicBuddySessionRecapResponse'),
      object({
        ownerId: uuid(),
        roomId: uuid(),
        owner: nullableRef('PublicUserResponse'),
        group: object({ id: uuid(), name: string(), slug: string(), visibility: enumString(['public', 'private']) }, ['id', 'name', 'slug', 'visibility'], { nullable: true }),
      }, ['ownerId', 'roomId', 'owner', 'group']),
    ],
  },
  BuddyRecapListItemResponse: { oneOf: [ref('BuddySessionRecapResponse'), ref('PublicBuddySessionRecapResponse')] },
  BuddyRecapListResponse: array(ref('BuddyRecapListItemResponse')),
  BuddyRecapShareResponse: object({ recap: ref('BuddySessionRecapResponse'), post: ref('FeedPostResponse'), target: enumString(['feed', 'group']) }, ['recap', 'post', 'target']),
  BuddyRoomReadResponse: object({ ok: boolean(), roomId: uuid(), userId: uuid(), readAt: dateTime(), user: nullableRef('PublicUserResponse') }, ['ok', 'roomId', 'userId', 'readAt', 'user']),

  HashtagResponse: object({ id: uuid(), name: string(), count: integer({ minimum: 0 }) }, ['id', 'name', 'count']),
  HashtagListResponse: array(ref('HashtagResponse')),
  SuggestedUserResponse: object({ id: uuid(), displayName: nullableString(), username: nullableString(), bio: nullableString(), profileImageUrl: nullableString() }, ['id', 'displayName', 'username', 'bio', 'profileImageUrl']),
  SuggestedUserListResponse: array(ref('SuggestedUserResponse')),
  SuggestedGroupResponse: object({ id: uuid(), name: string(), slug: string(), description: nullableString(), _count: object({ members: integer({ minimum: 0 }), posts: integer({ minimum: 0 }) }, ['members', 'posts']) }, ['id', 'name', 'slug', 'description', '_count']),
  SuggestedGroupListResponse: array(ref('SuggestedGroupResponse')),

  IntegrationResponse: object({
    id: uuid(),
    userId: uuid(),
    provider: enumString(['strava', 'garmin']),
    providerUserId: nullableString(),
    status: enumString(['connected', 'disconnected', 'revoked', 'error']),
    tokenExpiresAt: nullableDateTime(),
    scopes: array(string()),
    lastSyncAt: nullableDateTime(),
    lastSyncError: nullableString(),
    createdAt: dateTime(),
    updatedAt: dateTime(),
    _count: object({ activities: integer({ minimum: 0 }) }, ['activities']),
  }, ['id', 'userId', 'provider', 'providerUserId', 'status', 'tokenExpiresAt', 'scopes', 'lastSyncAt', 'lastSyncError', 'createdAt', 'updatedAt', '_count']),
  IntegrationListResponse: array(ref('IntegrationResponse')),
  IntegrationOAuthStartResponse: object({
    provider: enumString(['strava', 'garmin']),
    state: string(),
    authorizationUrl: nullableString(),
    message: string(),
  }, ['provider', 'state', 'authorizationUrl', 'message']),

  ActivityRecordResponse: object({
    id: uuid(),
    userId: uuid(),
    integrationId: nullableString(),
    source: enumString(['manual', 'strava', 'garmin']),
    externalId: nullableString(),
    type: string(),
    title: nullableString(),
    startedAt: dateTime(),
    durationSeconds: integer({ nullable: true, minimum: 0 }),
    distanceMeters: number({ nullable: true, minimum: 0 }),
    elevationGainMeters: number({ nullable: true, minimum: 0 }),
    calories: integer({ nullable: true, minimum: 0 }),
    averageHeartRate: integer({ nullable: true, minimum: 0 }),
    maxHeartRate: integer({ nullable: true, minimum: 0 }),
    averagePaceSecondsKm: integer({ nullable: true, minimum: 0 }),
    averageSpeedMetersSec: number({ nullable: true, minimum: 0 }),
    raw: nullableRef('JsonObject'),
    createdAt: dateTime(),
    updatedAt: dateTime(),
    integration: object({
      provider: enumString(['strava', 'garmin']),
      status: enumString(['connected', 'disconnected', 'revoked', 'error']),
    }, ['provider', 'status'], { nullable: true }),
    posts: array(object({ id: uuid(), visibility: enumString(postVisibility) }, ['id', 'visibility'])),
  }, ['id', 'userId', 'integrationId', 'source', 'externalId', 'type', 'title', 'startedAt', 'durationSeconds', 'distanceMeters', 'elevationGainMeters', 'calories', 'averageHeartRate', 'maxHeartRate', 'averagePaceSecondsKm', 'averageSpeedMetersSec', 'raw', 'createdAt', 'updatedAt']),
  ActivityRecordListResponse: array(ref('ActivityRecordResponse')),
  ActivityStatsResponse: object({
    window: enumString(['week', 'month', 'year', 'all']),
    totals: object({
      count: integer({ minimum: 0 }),
      durationSeconds: integer({ minimum: 0 }),
      distanceMeters: number({ minimum: 0 }),
      elevationGainMeters: number({ minimum: 0 }),
      calories: integer({ minimum: 0 }),
    }, ['count', 'durationSeconds', 'distanceMeters', 'elevationGainMeters', 'calories']),
    byType: array(object({
      type: string(),
      _count: object({ id: integer({ minimum: 0 }) }, ['id']),
      _sum: object({
        durationSeconds: integer({ nullable: true, minimum: 0 }),
        distanceMeters: number({ nullable: true, minimum: 0 }),
        calories: integer({ nullable: true, minimum: 0 }),
      }, ['durationSeconds', 'distanceMeters', 'calories']),
    }, ['type', '_count', '_sum'])),
    recent: array(object({
      id: uuid(),
      type: string(),
      title: nullableString(),
      startedAt: dateTime(),
      distanceMeters: number({ nullable: true, minimum: 0 }),
      durationSeconds: integer({ nullable: true, minimum: 0 }),
      calories: integer({ nullable: true, minimum: 0 }),
    }, ['id', 'type', 'title', 'startedAt', 'distanceMeters', 'durationSeconds', 'calories'])),
  }, ['window', 'totals', 'byType', 'recent']),

  NotificationActorResponse: object({
    id: uuid(), displayName: nullableString(), username: string(), profileImageUrl: nullableString(),
  }, ['id', 'displayName', 'username', 'profileImageUrl']),
  NotificationResponse: object({
    id: uuid(), type: string(), entityId: nullableString(), actorIds: array(uuid(), { nullable: true }), message: string(), readAt: nullableDateTime(), createdAt: dateTime(), actor: nullableRef('NotificationActorResponse'),
  }, ['id', 'type', 'entityId', 'actorIds', 'message', 'readAt', 'createdAt', 'actor']),
  NotificationListResponse: array(ref('NotificationResponse')),

  UploadResponse: object({
    key: string(),
    url: string(),
    path: string(),
    collection: enumString(['profile-photo', 'cover-photo', 'group-photo', 'chat-photo', 'actsnap-media', 'post-media', 'comment-media', 'generic-image', 'generic-video', 'generic-audio', 'generic-media']),
    filename: string(),
    originalName: string(),
    mimeType: string(),
    size: integer({ minimum: 0 }),
    type: enumString(['image', 'video', 'audio']),
    width: integer({ minimum: 0 }),
    height: integer({ minimum: 0 }),
  }, ['key', 'url', 'collection', 'filename', 'originalName', 'mimeType', 'size', 'type']),
  UploadBatchResponse: object({ files: array(ref('UploadResponse')) }, ['files']),

  StoryAuthorResponse: object({ id: uuid(), displayName: nullableString(), username: nullableString(), profileImageUrl: nullableString() }, ['id', 'displayName', 'username', 'profileImageUrl']),
  StoryReactionResponse: object({ storyId: uuid(), userId: uuid(), emoji: enumString(['🔥', '💪', '👏', '😍', '😂', '😮']), createdAt: dateTime(), updatedAt: dateTime(), user: ref('StoryAuthorResponse') }, ['storyId', 'userId', 'emoji', 'createdAt', 'updatedAt', 'user']),
  StoryFeedReactionResponse: object({ userId: uuid(), emoji: enumString(['🔥', '💪', '👏', '😍', '😂', '😮']), createdAt: dateTime() }, ['userId', 'emoji', 'createdAt']),
  StoryViewerReactionResponse: object({ userId: uuid(), emoji: enumString(['🔥', '💪', '👏', '😍', '😂', '😮']), createdAt: dateTime(), updatedAt: dateTime() }, ['userId', 'emoji', 'createdAt', 'updatedAt']),
  StoryResponse: object({
    id: uuid(), authorId: uuid(), text: nullableString(), textPlacement: enumString(['caption', 'overlay']), mediaUrl: nullableString(), mediaType: enumString(['image', 'video'], { nullable: true }), mimeType: nullableString(), filename: nullableString(), visibility: enumString(postVisibility), viewCount: integer({ minimum: 0 }), viewerCanManage: boolean(), expiresAt: dateTime(), createdAt: dateTime(), updatedAt: dateTime(), author: ref('StoryAuthorResponse'), views: array(object({ userId: uuid(), viewedAt: dateTime() }, ['userId', 'viewedAt'])), reactions: array(ref('StoryFeedReactionResponse')),
  }, ['id', 'authorId', 'text', 'textPlacement', 'mediaUrl', 'mediaType', 'mimeType', 'filename', 'visibility', 'viewCount', 'viewerCanManage', 'expiresAt', 'createdAt', 'updatedAt', 'author', 'views', 'reactions']),
  StoryGroupResponse: object({ author: ref('StoryAuthorResponse'), stories: array(ref('StoryResponse')), hasUnseen: boolean(), latestCreatedAt: dateTime() }, ['author', 'stories', 'hasUnseen', 'latestCreatedAt']),
  StoryGroupListResponse: array(ref('StoryGroupResponse')),
  StoryViewResponse: object({ storyId: uuid(), userId: uuid(), viewedAt: dateTime(), user: ref('StoryAuthorResponse'), reaction: nullableRef('StoryViewerReactionResponse') }, ['storyId', 'userId', 'viewedAt', 'user', 'reaction']),
  StoryViewListResponse: array(ref('StoryViewResponse')),
  ActiveStoryAuthorResponse: object({ authorId: uuid(), storyId: uuid() }, ['authorId', 'storyId']),
  ActiveStoryAuthorListResponse: array(ref('ActiveStoryAuthorResponse')),
  StoryReplyResponse: { oneOf: [ref('MessageRequestResponse'), ref('ChatMessageResponse')] },

  KlipyMediaResponse: object({ id: string(), title: string(), url: string(), previewUrl: string(), width: integer({ nullable: true, minimum: 0 }), height: integer({ nullable: true, minimum: 0 }), source: enumString(['klipy']), kind: enumString(['gifs', 'stickers']) }, ['id', 'title', 'url', 'previewUrl', 'width', 'height', 'source', 'kind']),
  KlipyResponse: object({ configured: boolean(), next: string({ nullable: true }), results: array(ref('KlipyMediaResponse')) }, ['configured', 'next', 'results']),
};
